FROM microsoft/aspnetcore-build:2.0.3 as build

WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish --output /out --configuration Release

FROM microsoft/aspnetcore:2.0.3
WORKDIR app
COPY --from=build /out .
ENTRYPOINT [ "dotnet", "Hello.dll"]